[build]
  publish = "web"
  command = ""

# Proxy API calls to your Render backend FastAPI server
[[redirects]]
  from = "/api/*"
  to = "https://dynasty-agent-backend.onrender.com/api/:splat"
  status = 200
  force = true

# SPA-style fallback to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: security headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"